[package]
name = "ucas-http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libevent = { path = "../libevent-rs" }
openssl = { path = "../rust-openssl/openssl", version = "0.10.38" }